Update main.py
Ignore false positive (since the application is already running in the port it gives this error):

```
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 2327, in launch
    ) = http_server.start_server(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/http_server.py", line 154, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 8080-8080. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`
```